# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e4f217c6a6298dfe46d395530bb18bada4da5db2295b7bad36d32a863515bf896abcf6daabe8c5dd45d53291475cdd74a9d2fe7def400424efa44e178fdebc8

test:
  secret_key_base: 77b4e8a21130e8fb79e347249f8a05e446015e0145010ef60714c1c2610aaa97574933685e6c3cdb575baef4a130385dadd483c217939b9489ea199c7c0a5914

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
